refactor: remove old demos and update readme
atsign-foundation/at_demos pull request #116
Opened 2023-06-14 16:41 UTC by HamdaanAliQuatil

Closes #108 

**- What I did**

Remove old demos and update the readme accordingly

**- How I did it**

- [x] Remove at_cookbook and at_hello_world demos.
- [x] Updated README to remove at_cookbook, at_hello_world demos and add sshnp_docker_demo.

**- Description for the changelog**

remove old demos and update readme

2023-06-22 23:28 UTC, JeremyTubongbanua commented
also have new notifications demo #111

2023-06-26 18:00 UTC, JeremyTubongbanua commented
Thank you, @HamdaanAliQuatil :)

2023-07-06 15:23 UTC, JeremyTubongbanua approved these changes, later dismissed

2023-07-06 15:28 UTC, JeremyTubongbanua submitted a review, later dismissed

2023-07-06 15:29 UTC, JeremyTubongbanua approved these changes

2023-07-06 15:30 UTC, xavierchanth commented
Thanks for doing this @HamdaanAliQuatil

2023-07-06 15:31 UTC, XavierChanth submitted a review, later dismissed

2023-07-06 15:31 UTC, JeremyTubongbanua submitted a review, later dismissed

2023-07-06 21:22 UTC, TylerTrott requested changes
Few simple typos

2023-07-06 21:22 UTC, TylerTrott commented on README.md
Typo: `sshnp_docker_demo`: A demo of to establish an

Should be: `sshnp_docker_demo`: A demo to establish an

2023-07-06 21:22 UTC, TylerTrott commented on README.md
Typo: `at_notifications`: A demo of using `.notify` and `.subscribe`

Should be: `at_notifications`: A demo using `.notify` and `.subscribe`

2023-07-06 21:22 UTC, TylerTrott commented on at_notifications/README.md
Typo: This is a demo of using `.notify` and `.subscribe` 

Should be: This is a demo using `.notify` and `.subscribe`

2023-07-06 21:22 UTC, TylerTrott commented on at_notifications/README.md
Typo: `subscribe-to-notifier.dart` @subscriber is listens for notifications received from @notifier

Should be: `subscribe-to-notifier.dart` @subscriber listens for notifications received from @notifier

2023-07-06 21:22 UTC, TylerTrott commented on at_notifications/README.md
Typo:  To run this demo, you will need 2 atSigns and thier .atKeys in `~/.atsign/keys` directory.

Should be:  To run this demo, you will need 2 atSigns and their .atKeys in `~/.atsign/keys` directory.

2023-07-07 23:51 UTC, JeremyTubongbanua approved these changes, later dismissed

2023-07-07 23:52 UTC, JeremyTubongbanua approved these changes

2023-07-08 00:29 UTC, TylerTrott approved these changes
Lgtm

2023-07-08 00:29 UTC, merged