Adding Documentation for sshnp on Raspberry Pi
atsign-foundation/at_demos pull request #143
Opened 2023-11-21 23:48 UTC by TylerTrott

**- What I did**
Created a step by step guide on installing sshnp on a raspberry pi

**- How I did it**
Local edits and going through each step myself to confirm validity 

**- How to verify it**
walkthrough steps on your own pi :) 

**- Description for the changelog**
Adding Documentation for sshnp on Raspberry Pi

2023-11-22 09:38 UTC, cpswan requested changes

2023-11-22 09:38 UTC, cpswan commented on sshnp_raspberrypi_demo/README.md
> +- Raspberry Pi 4 Model B
3 or 4? It says 3 above.

2023-11-22 09:38 UTC, cpswan commented on sshnp_raspberrypi_demo/README.md
> +You can download the latest version of Raspberry Pi OS (previously called Raspbian) from the official website [here](https://www.raspberrypi.org/downloads/raspbian/). Follow the instructions on the w
Raspbian (above) is the old name

2023-11-22 09:38 UTC, cpswan commented on sshnp_raspberrypi_demo/README.md
> +You can download the latest version of Raspberry Pi OS (previously called Raspbian) from the official website [here](https://www.raspberrypi.org/downloads/raspbian/). Follow the instructions on the w
That link now redirects to https://www.raspberrypi.com/software/

2023-11-22 17:37 UTC, TylerTrott commented on sshnp_raspberrypi_demo/README.md
> +- Raspberry Pi 4 Model B
whoops, Pi 4, good catch

2023-11-23 15:05 UTC, JeremyTubongbanua approved these changes

2023-11-23 15:09 UTC, JeremyTubongbanua requested changes
Do you think we could add this demo to the running list of demos in the root `./README.md` with a short description?

![image](https://github.com/atsign-foundation/at_demos/assets/79019866/0f4fa714-2d8e-436e-9e33-dac0ec20d795)

2023-11-27 19:01 UTC, TylerTrott commented
> Do you think we could add this demo to the running list of demos in the root `./README.md` with a short description?
> 
> ![image](https://private-user-images.githubusercontent.com/79019866/285247454-0f4fa714-2d8e-436e-9e33-dac0ec20d795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMTE5NTEsIm5iZiI6MTcwMTExMTY1MSwicGF0aCI6Ii83OTAxOTg2Ni8yODUyNDc0NTQtMGY0ZmE3MTQtMmQ4ZS00MzZlLTllMzMtZGFjMGVjMjBkNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE5MDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZWFjMzYxZWY5OGI0MjI2YTc2YjhiZWQxMWY2OTI1MWRiODU5OTYwNmU3MWUwY2JmN2U5MmY4NmNlMjhlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P-1J3nc-H6nB3sfhy0JYBOFLRkaql-yL7UK4fqtpBEw)

This has been resolved

2023-11-27 19:09 UTC, JeremyTubongbanua submitted a review, later dismissed

2023-11-28 17:40 UTC, cpswan approved these changes, later dismissed

2023-12-05 17:18 UTC, JeremyTubongbanua approved these changes

2023-12-08 15:11 UTC, cpswan approved these changes

2023-12-11 04:24 UTC, merged