chore: organize demos
atsign-foundation/at_demos pull request #216
Opened 2024-08-06 15:53 UTC by XavierChanth

**- What I did**

- Moved all demos into demos/
- Moved at_demo_data into packages/

**- How I did it**

**- How to verify it**

**- Description for the changelog**
chore: organize demos

2024-08-07 09:24 UTC, cpswan commented
@XavierChanth is this ready to review now?

2024-08-07 18:47 UTC, XavierChanth commented
> @XavierChanth is this ready to review now?

Yes it is

2024-08-08 08:51 UTC, cpswan requested changes
Mostly LGTM, but one change that looks accidental, and also `mwc_demo/dart/iot_sender/bin/.set_hro2_receivers.dart.un~` shouldn't be there, so let's use this opportunity to get rid.

2024-08-08 08:51 UTC, cpswan commented on .github/workflows/static_analysis.yml
> +      # It needs to look at pubspec.lock ranls, which is why it's
What's a `ranls`?

2024-08-08 14:32 UTC, XavierChanth commented on .github/workflows/static_analysis.yml
> +      # It needs to look at pubspec.lock ranls, which is why it's
accidental change...

2024-08-08 14:51 UTC, cpswan approved these changes

2024-08-08 14:53 UTC, cpswan commented
@XavierChanth can we also lose the stray vim undo file at `mwc_demo/dart/iot_sender/bin/.set_hro2_receivers.dart.un~`

2024-08-08 15:02 UTC, XavierChanth commented
> @XavierChanth can we also lose the stray vim undo file at `mwc_demo/dart/iot_sender/bin/.set_hro2_receivers.dart.un~`

That was a delete

2024-08-08 15:02 UTC, merged